api:
  key_file: api.key

postgres:
  host: localhost
  port: 5432
  dbname: financials
  user: postgres
  password: ""

etfs:
  symbols:
    - SPY
    - XLK
    - XLF
    - XLE
    - XLV
    - XLI
    - XLP
    - XLY
    - XLU
    - XLB
    - XLRE
