CREATE TABLE IF NOT EXISTS etf_metadata (
    etf TEXT PRIMARY KEY,
    name TEXT NOT NULL
);

INSERT INTO etf_metadata (etf, name) VALUES
    ('AGG', 'Core US Aggregate Bond'),
    ('BND', 'Total Bond Market'),
    ('CORN', 'Corn'),
    ('CPER', 'Copper'),
    ('DBA', 'Agriculture'),
    ('DBB', 'Base Metals'),
    ('DBC', 'Broad Commodities'),
    ('EEM', 'Emerging Markets'),
    ('EFA', 'EAFE'),
    ('EMB', 'EM USD Bonds'),
    ('EWG', 'Germany'),
    ('EWJ', 'Japan'),
    ('EWU', 'United Kingdom'),
    ('EWZ', 'Brazil'),
    ('FXI', 'China Large Cap'),
    ('GDX', 'Gold Miners'),
    ('GLD', 'Gold'),
    ('HYG', 'High Yield Corporate Bonds'),
    ('IEFA', 'Core EAFE'),
    ('INDA', 'India'),
    ('JNK', 'High Yield Bonds'),
    ('LQD', 'Investment Grade Corporate Bonds'),
    ('PALL', 'Palladium'),
    ('PDBC', 'Diversified Commodities'),
    ('PPLT', 'Platinum'),
    ('SLV', 'Silver'),
    ('SOYB', 'Soybeans'),
    ('SPY', 'S&P 500'),
    ('TIP', 'TIPS'),
    ('TLT', '20+ Year Treasuries'),
    ('UNG', 'Natural Gas'),
    ('URA', 'Uranium'),
    ('USO', 'Oil'),
    ('VEA', 'Developed Markets'),
    ('VWO', 'Emerging Markets Ex US'),
    ('WEAT', 'Wheat'),
    ('XLB', 'Materials Sector'),
    ('XLC', 'Communication Services Sector'),
    ('XLE', 'Energy Sector'),
    ('XLF', 'Financial Sector'),
    ('XLI', 'Industrial Sector'),
    ('XLK', 'Technology Sector'),
    ('XLP', 'Consumer Staples Sector'),
    ('XLRE', 'Real Estate Sector'),
    ('XLU', 'Utilities Sector'),
    ('XLV', 'Health Care Sector'),
    ('XLY', 'Consumer Discretionary Sector')
ON CONFLICT (etf) DO UPDATE SET name = EXCLUDED.name;
